const defaultData={title:'DOLOMITES & LAVENDER',subtitle:'ทริปท่องเที่ยว',tripType:'Photography Journey',startDate:'2026-07-04',endDate:'2026-07-12',intro:'เดินทางสู่ทางตอนเหนือของประเทศอิตาลีในฤดูร้อน ชมเทือกเขาหินปูนรูปทรงแหลมอันเป็นเอกลักษณ์ พร้อมเส้นทาง hiking ระดับโลก และปิดท้ายด้วยทุ่งลาเวนเดอร์สุดลูกหูลูกตาที่ฝรั่งเศส',groupSize:'12 ท่าน + 2 ทริปลีดเดอร์',transport:'รถตู้ 9 ที่นั่ง จำนวน 2 คัน',meetingPoint:'สนามบินสุวรรณภูมิ',destinations:'ฝรั่งเศส · เยอรมนี · อิตาลี',timezone:'ช้ากว่าไทย 5 ชั่วโมง',weather:'3–30°C ตามพื้นที่และช่วงเวลา',currency:'Euro (EUR)',flights:'TG924  BKK → MUC  00:50–07:05\nLH2262  MUC → MRS  11:15–12:55\nLH2263  MRS → MUC  13:45–15:20\nTG925  MUC → BKK  14:25–06:05 (+1)',hotels:'Ibis Manosque Cadarache · 2 คืน\nB&B Hotel Passo Tre Croci Cortina · 3 คืน\nHotel Schmuckhof · 2 คืน',leaders:'เอกพล มณีโชติ (โคล)  089-008-9395\nประนิธิ ศรีชัยสันติกุล (หมี)  089-002-9920',emergency:'สถานเอกอัครราชทูต ณ กรุงโรม\n+39 (06) 8622-051 · info@ambthai.it',notes:'สถานที่ท่องเที่ยวอาจปรับเปลี่ยนตามสภาพอากาศและความเหมาะสมหน้างาน ทริปลีดเดอร์จะแจ้งสรุปโปรแกรมในแต่ละวันอีกครั้ง',documents:'Passport และ Visa\nItinerary และใบจองโรงแรม\nสำเนาพาสปอร์ตและวีซ่า\nสำเนาตั๋วเครื่องบิน\nประกันการเดินทาง',packing:'กระเป๋าเดินทางไม่เกิน 28 นิ้ว 1 ใบ\nกระเป๋าเป้สำหรับของใช้ระหว่างวัน\nรองเท้าเดินป่า / รองเท้าผ้าใบ\nไม้เท้าเดินป่า\nเสื้อกันหนาวแบบ layer\nหมวกและถุงมือ\nครีมกันแดดและแว่นกันแดด\nPower bank ไม่เกิน 20,000 mAh\nหัวแปลงปลั๊กยุโรป 2 ขากลม\nยาประจำตัวและของใช้ส่วนตัว',cover:'assets/dolomite-cover.jpg',days:[
{date:'3 ก.ค. 2569',place:'Bangkok',title:'วันนัดหมาย',detail:'22:00  พร้อมกันที่สนามบินสุวรรณภูมิ เช็กอินกับการบินไทย และพบกันที่ประตูขึ้นเครื่อง',hotel:'เที่ยวบินข้ามคืน'},
{date:'4 ก.ค. 2569',place:'Bangkok · Munich · Marseille · Valensole',title:'ออกเดินทางสู่ยุโรป',detail:'เช้า  เดินทางถึงมิวนิก ผ่านพิธีตรวจคนเข้าเมืองและต่อเที่ยวบินไป Marseille\nบ่าย  รับรถเช่า แวะ supermarket และเดินทางสู่ Valensole\nเย็น  เก็บภาพแสงเย็นที่ทุ่งลาเวนเดอร์',hotel:'Ibis Manosque Cadarache'},
{date:'5 ก.ค. 2569',place:'Valensole',title:'Lavender day',detail:'เช้า  เก็บภาพแสงเช้าที่ทุ่งลาเวนเดอร์รอบ Provence\nกลางวัน  เยี่ยมชม Abbaye Notre-Dame de Sénanque\nบ่าย  ชมฟาร์ม Lavandes Angelvin และเก็บภาพช่วงเย็น',hotel:'Ibis Manosque Cadarache'},
{date:'6 ก.ค. 2569',place:'Marseille · Munich · Cortina d’Ampezzo',title:'เข้าสู่ Dolomites',detail:'เช้า  เช็กเอาต์และเดินทางไปสนามบิน Marseille\nบ่าย  บินสู่ Munich รับรถเช่า และเดินทางประมาณ 4–5 ชั่วโมงสู่ Cortina d’Ampezzo',hotel:'B&B Hotel Passo Tre Croci Cortina'},
{date:'7 ก.ค. 2569',place:'Cortina d’Ampezzo',title:'Cadini · Cinque Torri · Tre Cime',detail:'เช้า  Hiking สู่จุดชมวิว Cadini di Misurina ระยะทางไปกลับ 3.3 กม.\nบ่าย  นั่งกระเช้าชม Cinque Torri\nเย็น  เดินไปเก็บภาพ Tre Cime กับเงาสะท้อน ระยะทางไปกลับ 3.8 กม.',hotel:'B&B Hotel Passo Tre Croci Cortina'},
{date:'8 ก.ค. 2569',place:'Cortina d’Ampezzo',title:'Giau Pass · Rifugio Locatelli',detail:'เช้า  เก็บภาพที่ Giau Pass\nบ่าย  พักผ่อนและเตรียมตัวสำหรับ trail ช่วงเย็น\nเย็น  Hiking สู่ Rifugio Locatelli ระยะทางไปกลับ 8.2 กม.',hotel:'B&B Hotel Passo Tre Croci Cortina'},
{date:'9 ก.ค. 2569',place:'Cortina d’Ampezzo · Chiusa',title:'Lake day',detail:'เช้า  ถ่ายภาพ Lake Misurina และเช็กเอาต์\nสาย  ชม Lago di Braies และพายเรือ\nเย็น  ชมพระอาทิตย์ตกที่ Gardena Pass',hotel:'Hotel Schmuckhof'},
{date:'10 ก.ค. 2569',place:'Ortisei',title:'Alpe di Siusi · Seceda',detail:'เช้า  ชม Lago di Carezza และขึ้นกระเช้าสู่ Alpe di Siusi\nบ่าย  ขึ้นกระเช้าไปชมยอดเขาฟันเลื่อย Seceda\nเย็น  ถ่ายภาพหมู่บ้าน Santa Maddalena',hotel:'Hotel Schmuckhof'},
{date:'11–12 ก.ค. 2569',place:'Munich · Bangkok',title:'เดินทางกลับ',detail:'เช้า  เดินทางสู่สนามบิน Munich\nบ่าย  เดินทางกลับกรุงเทพฯ ด้วยเที่ยวบิน TG925\nวันถัดมา  เดินทางถึงกรุงเทพฯ โดยสวัสดิภาพ',hotel:'—'}]};
let data=JSON.parse(localStorage.getItem('tripprep-data')||'null')||structuredClone(defaultData);data.gallery=data.gallery||[];data.design=data.design||'alpine';let scale=.72;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmtDate(v){if(!v)return'—';return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v+'T12:00:00'))}function lines(v){return String(v||'').split('\n').filter(Boolean)}
function highResImage(src){if(!/^https?:/i.test(src||''))return src;try{const u=new URL(src);u.pathname=u.pathname.replace(/-\d{2,5}x\d{2,5}(?=\.(?:jpe?g|png|webp|avif)$)/i,'');return u.href}catch{return src}}
function header(title,n,label='TRIP INFORMATION'){return `<div class="page-header"><div><div class="section-label">${label}</div><h3>${esc(title)}</h3></div><div class="page-no">${String(n).padStart(2,'0')}</div></div>`}function footer(){return `<div class="footer-mark">TRIPPREP · ${esc(data.title)}</div>`}
function render(){let p=1;let html=`<article class="page cover"><div class="cover-photo" style="background-image:url('${esc(highResImage(data.cover))}')"></div><div class="cover-content"><div class="cover-kicker">${esc(data.tripType)}</div><h2>${esc(data.title)}</h2><div class="cover-meta"><span>${esc(data.subtitle)}</span><span>${fmtDate(data.startDate)}<br>— ${fmtDate(data.endDate)}</span></div></div></article>`;
html+=`<article class="page"><div class="page-inner">${header('รู้จักทริปนี้',++p)}<p class="lead">${esc(data.intro)}</p><div class="facts"><div class="fact"><small>Destination</small><strong>${esc(data.destinations)}</strong></div><div class="fact"><small>Travel dates</small><strong>${fmtDate(data.startDate)} — ${fmtDate(data.endDate)}</strong></div><div class="fact"><small>Group</small><strong>${esc(data.groupSize)}</strong></div><div class="fact"><small>Transport</small><strong>${esc(data.transport)}</strong></div><div class="fact"><small>Meeting point</small><strong>${esc(data.meetingPoint)}</strong></div><div class="fact"><small>Trip style</small><strong>${esc(data.tripType)}</strong></div></div>${footer()}</div></article>`;
html+=`<article class="page"><div class="page-inner">${header('ข้อมูลสำคัญ',++p)}<div class="facts"><div class="fact"><small>Time zone</small><strong>${esc(data.timezone)}</strong></div><div class="fact"><small>Weather</small><strong>${esc(data.weather)}</strong></div><div class="fact"><small>Currency</small><strong>${esc(data.currency)}</strong></div><div class="fact"><small>Emergency</small><strong>${esc(data.emergency).replace(/\n/g,'<br>')}</strong></div></div><div class="block-title">เที่ยวบิน</div><div class="text-block">${esc(data.flights)}</div><div class="block-title">ที่พัก</div><div class="text-block">${esc(data.hotels)}</div><div class="block-title">ผู้ดูแลทริป</div><div class="text-block">${esc(data.leaders)}</div>${footer()}</div></article>`;
html+=`<article class="page"><div class="page-inner">${header('เตรียมตัวก่อนเดินทาง',++p)}<div class="block-title">DOCUMENT CHECKLIST</div><div class="checklist">${lines(data.documents).map(x=>`<div class="check-item"><i class="check"></i><span>${esc(x)}</span></div>`).join('')}</div><div class="block-title">PACKING LIST</div><div class="checklist">${lines(data.packing).map(x=>`<div class="check-item"><i class="check"></i><span>${esc(x)}</span></div>`).join('')}</div><div class="block-title">หมายเหตุสำคัญ</div><div class="text-block">${esc(data.notes)}</div>${footer()}</div></article>`;
data.days.forEach((d,i)=>{html+=`<article class="page itinerary-page"><div class="page-inner">${header('กำหนดการเดินทาง',++p,'ITINERARY')}<div class="day-hero"><div class="day-badge"><span>DAY</span><b>${i}</b></div><div class="day-title"><h3>${esc(d.title)}</h3><p>${esc(d.place)} · ${esc(d.date)}</p></div></div><div class="schedule"><p>${esc(d.detail)}</p></div><div class="hotel"><strong>ที่พัก</strong> &nbsp; ${esc(d.hotel)}</div>${footer()}</div></article>`});
for(let i=0;i<data.gallery.length;i+=4){const photos=data.gallery.slice(i,i+4);html+=`<article class="page"><div class="page-inner">${header('ภาพบรรยากาศ',++p,'PHOTO GALLERY')}<div class="gallery-grid ${photos.length===1?'single':''}">${photos.map(src=>`<figure><img src="${esc(highResImage(src))}" alt="Trip photo"></figure>`).join('')}</div>${footer()}</div></article>`}
html+=`<article class="page"><div class="page-inner">${header('Trip at a glance',++p,'SUMMARY')}<table class="summary-table">${data.days.map((d,i)=>`<tr><td>DAY ${i}<br>${esc(d.date)}</td><td><strong>${esc(d.place)}</strong><br>${esc(d.title)}<br><span style="color:#7b8981">${esc(d.hotel)}</span></td></tr>`).join('')}</table>${footer()}</div></article>`;$('#documentPreview').innerHTML=html;$('#pageCount').textContent=`${p} หน้า`;document.documentElement.style.setProperty('--scale',scale);$('#zoomLabel').textContent=Math.round(scale*100)+'%'}
function renderEditor(){document.querySelectorAll('[data-field]').forEach(el=>el.value=data[el.dataset.field]||'');$('#daysEditor').innerHTML=data.days.map((d,i)=>`<div class="day-card"><div class="day-card-head"><strong>DAY ${i}</strong><button data-remove="${i}">ลบ</button></div><div class="grid2"><label>วันที่<input data-day="${i}" data-key="date" value="${esc(d.date)}"></label><label>สถานที่<input data-day="${i}" data-key="place" value="${esc(d.place)}"></label></div><label>หัวข้อ<input data-day="${i}" data-key="title" value="${esc(d.title)}"></label><label>กำหนดการ<textarea rows="5" data-day="${i}" data-key="detail">${esc(d.detail)}</textarea></label><label>ที่พัก<input data-day="${i}" data-key="hotel" value="${esc(d.hotel)}"></label></div>`)}
let saveTimer;function save(){clearTimeout(saveTimer);$('#saveState').textContent='กำลังบันทึก…';saveTimer=setTimeout(()=>{localStorage.setItem('tripprep-data',JSON.stringify(data));$('#saveState').textContent='บันทึกแล้ว'},350)}document.addEventListener('input',e=>{if(e.target.dataset.field){data[e.target.dataset.field]=e.target.value;save();render()}if(e.target.dataset.day){data.days[+e.target.dataset.day][e.target.dataset.key]=e.target.value;save();render()}});document.addEventListener('click',e=>{if(e.target.matches('.tab')){document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');$('#'+e.target.dataset.tab).classList.add('active')}if(e.target.dataset.remove){data.days.splice(+e.target.dataset.remove,1);renderEditor();save();render()}});
$('#addDayBtn').onclick=()=>{data.days.push({date:'',place:'',title:'วันเดินทางใหม่',detail:'',hotel:''});renderEditor();save();render()};$('#coverUpload').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{data.cover=r.result;save();render()};r.readAsDataURL(f)};$('#printBtn').onclick=()=>window.print();$('#resetBtn').onclick=()=>{if(confirm('ล้างข้อมูลทั้งหมดและกลับไปใช้ตัวอย่างเริ่มต้น?')){data=structuredClone(defaultData);data.gallery=[];localStorage.removeItem('tripprep-data');renderEditor();render()}};$('#zoomIn').onclick=()=>{scale=Math.min(1,scale+.08);render()};$('#zoomOut').onclick=()=>{scale=Math.max(.4,scale-.08);render()};
let imported=null,selected=new Set();const dialog=$('#importDialog');$('#importLaunch').onclick=()=>dialog.showModal();function pool(){if(!imported)return;$('#mediaPool').innerHTML=imported.images.map((src,i)=>`<div class="media-card ${selected.has(i)?'selected':''} ${data.cover===src?'is-cover':''}" data-media="${i}"><img src="${esc(src)}" loading="lazy" alt="Imported photo ${i+1}"><span class="select-mark">✓</span><button class="cover-action" data-cover-index="${i}">ใช้เป็นภาพปก</button></div>`).join('')}
$('#importBtn').onclick=async()=>{const url=$('#importUrl').value.trim(),status=$('#importStatus');status.className='import-status loading';status.textContent='กำลังอ่านหน้าเว็บและรวบรวมรูปภาพ…';$('#importContent').hidden=true;selected.clear();try{if(location.protocol==='file:')throw new Error('กรุณาเปิดผ่าน local server: node server.mjs แล้วเข้า http://localhost:4173');const r=await fetch('/api/import?url='+encodeURIComponent(url));const result=await r.json();if(!r.ok)throw new Error(result.error||'นำเข้าไม่สำเร็จ');imported=result;$('#foundTitle').textContent=result.title||'ไม่พบชื่อ';$('#foundCount').textContent=`${result.images.length} รูป`;status.className='import-status';status.textContent=`นำเข้าจาก ${new URL(result.sourceUrl).hostname} สำเร็จ`;$('#importContent').hidden=false;pool()}catch(e){status.className='import-status error';status.textContent=e.message}};
$('#mediaPool').onclick=e=>{const cover=e.target.closest('[data-cover-index]');if(cover){e.stopPropagation();data.cover=imported.images[+cover.dataset.coverIndex];save();render();pool();return}const card=e.target.closest('[data-media]');if(!card)return;const i=+card.dataset.media;selected.has(i)?selected.delete(i):selected.add(i);pool()};$('#applyTextBtn').onclick=()=>{if(!imported)return;if(imported.title)data.title=imported.title.replace(/\s*[–|-]\s*Pixelmate.*$/i,'');if(imported.description)data.intro=imported.description;renderEditor();save();render();$('#importStatus').textContent='นำชื่อและรายละเอียดมาใช้แล้ว'};$('#addSelectedBtn').onclick=()=>{if(!imported||!selected.size)return;data.gallery=[...new Set([...data.gallery,...[...selected].map(i=>imported.images[i])])];save();render();$('#importStatus').textContent=`เพิ่ม ${selected.size} รูปเข้าเอกสารแล้ว`;selected.clear();pool()};renderEditor();render();
