import{initializeApp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import{getFirestore,doc,setDoc,collection,getDocs}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const firebaseConfig={projectId:'pixelmate-tripprep-2026',appId:'1:826579773090:web:c63f13421a95132a23d9fb',storageBucket:'pixelmate-tripprep-2026.firebasestorage.app',apiKey:'AIzaSyBfKQLqiPxcrbW3Z4yldxJBVF-9eY4Wk3A',authDomain:'pixelmate-tripprep-2026.firebaseapp.com',messagingSenderId:'826579773090'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),button=document.querySelector('#firebaseBtn');let user=null,saveTimer;
async function pushProject(project){if(!user)return;await setDoc(doc(db,'users',user.uid,'projects',project.id),{name:project.name,updatedAt:project.updatedAt,data:project.data},{merge:true})}
async function pullProjects(){const snapshot=await getDocs(collection(db,'users',user.uid,'projects'));const records=snapshot.docs.map(item=>({id:item.id,...item.data()}));window.TripPrepBridge.mergeCloudProjects(records);await pushProject(window.TripPrepBridge.getCurrent())}
button.addEventListener('click',async()=>{try{if(user)await signOut(auth);else await signInWithPopup(auth,new GoogleAuthProvider())}catch(error){alert('เชื่อม Firebase ไม่สำเร็จ: '+error.message)}});
window.addEventListener('tripprep-local-save',event=>{clearTimeout(saveTimer);if(user)saveTimer=setTimeout(()=>pushProject(event.detail).catch(console.error),800)});
onAuthStateChanged(auth,async current=>{user=current;button.classList.toggle('connected',!!user);button.textContent=user?`☁ ${user.displayName||user.email||'เชื่อมแล้ว'}`:'☁ เชื่อม Firebase';button.title=user?'คลิกเพื่อออกจาก Firebase':'เข้าสู่ระบบด้วย Google';if(user){try{await pullProjects()}catch(error){console.error(error);alert('อ่านข้อมูล Firebase ไม่สำเร็จ: '+error.message)}}});
