const PROJECT_INDEX_KEY='tripprep-project-index';
const ACTIVE_PROJECT_KEY='tripprep-active-project';
const LEGACY_KEY='tripprep-data';
let projectIndex=JSON.parse(localStorage.getItem(PROJECT_INDEX_KEY)||'null')||[];
let activeProjectId=localStorage.getItem(ACTIVE_PROJECT_KEY)||'';
if(!projectIndex.length){activeProjectId='project-'+Date.now();projectIndex=[{id:activeProjectId,name:data.title||'โปรเจกต์แรก',updatedAt:Date.now()}];localStorage.setItem(`tripprep-project:${activeProjectId}`,JSON.stringify(data))}
if(!projectIndex.some(p=>p.id===activeProjectId))activeProjectId=projectIndex[0].id;
const storedActive=JSON.parse(localStorage.getItem(`tripprep-project:${activeProjectId}`)||'null');
if(storedActive){data=storedActive;data.gallery=data.gallery||[];renderEditor();render()}
const originalSave=save;
save=function(){originalSave();const item=projectIndex.find(p=>p.id===activeProjectId);if(item){item.updatedAt=Date.now();item.name=document.querySelector('#projectName').value.trim()||data.title||'ไม่มีชื่อ'}localStorage.setItem(`tripprep-project:${activeProjectId}`,JSON.stringify(data));localStorage.setItem(PROJECT_INDEX_KEY,JSON.stringify(projectIndex));localStorage.setItem(ACTIVE_PROJECT_KEY,activeProjectId)};
function currentProject(){return projectIndex.find(p=>p.id===activeProjectId)}
function applyFontScale(){document.querySelectorAll('.page').forEach(page=>page.style.setProperty('--fs-scale',data.fontScale||1))}function syncProjectUI(){const p=currentProject();document.querySelector('#projectName').value=p?.name||data.title||'TripPrep';applyFontScale();document.querySelector('#fontLabel').textContent=Math.round((data.fontScale||1)*100)+'%'}
function renderProjects(){document.querySelector('#projectsList').innerHTML=[...projectIndex].sort((a,b)=>b.updatedAt-a.updatedAt).map(p=>`<div class="project-row ${p.id===activeProjectId?'active':''}" data-open-project="${p.id}"><div><strong>${esc(p.name)}</strong><small>แก้ไขล่าสุด ${new Date(p.updatedAt).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'})}</small></div>${projectIndex.length>1?`<button data-delete-project="${p.id}">ลบ</button>`:''}</div>`).join('')}
function switchProject(id){save();const next=JSON.parse(localStorage.getItem(`tripprep-project:${id}`)||'null');if(!next)return;activeProjectId=id;data=next;data.gallery=data.gallery||[];localStorage.setItem(ACTIVE_PROJECT_KEY,id);renderEditor();render();syncProjectUI();document.querySelector('#projectsDialog').close()}
document.querySelector('#projectName').addEventListener('input',save);
document.querySelector('#openProjectsBtn').onclick=()=>{renderProjects();document.querySelector('#projectsDialog').showModal()};
document.querySelector('#newProjectBtn').onclick=()=>{const name=prompt('ชื่อโปรเจกต์ใหม่','ทริปใหม่');if(!name)return;save();activeProjectId='project-'+Date.now();data=structuredClone(defaultData);data.title=name;data.gallery=[];projectIndex.unshift({id:activeProjectId,name,updatedAt:Date.now()});renderEditor();render();syncProjectUI();save()};
document.querySelector('#projectsList').onclick=e=>{const del=e.target.closest('[data-delete-project]');if(del){e.stopPropagation();if(!confirm('ลบโปรเจกต์นี้ถาวร?'))return;const id=del.dataset.deleteProject;projectIndex=projectIndex.filter(p=>p.id!==id);localStorage.removeItem(`tripprep-project:${id}`);renderProjects();save();return}const row=e.target.closest('[data-open-project]');if(row)switchProject(row.dataset.openProject)};
document.querySelector('#exportJsonBtn').onclick=()=>{save();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(currentProject()?.name||data.title||'TripPrep').replace(/[\\/:*?"<>|]/g,'')+'.json';a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#importJsonBtn').onclick=()=>document.querySelector('#jsonFile').click();document.querySelector('#jsonFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const next=JSON.parse(reader.result);if(!next||typeof next!=='object')throw new Error('รูปแบบข้อมูลไม่ถูกต้อง');data=next;data.gallery=data.gallery||[];renderEditor();render();syncProjectUI();save();alert('นำเข้าข้อมูลเรียบร้อย')}catch(err){alert('เปิดไฟล์ไม่ได้: '+err.message)}};reader.readAsText(file);e.target.value=''};
function changeFont(delta){data.fontScale=Math.max(.8,Math.min(1.25,+((data.fontScale||1)+delta).toFixed(2)));applyFontScale();document.querySelector('#fontLabel').textContent=Math.round(data.fontScale*100)+'%';save()}
document.querySelector('#fontOut').onclick=()=>changeFont(-.05);document.querySelector('#fontIn').onclick=()=>changeFont(.05);new MutationObserver(applyFontScale).observe(document.querySelector('#documentPreview'),{childList:true});syncProjectUI();save();
